codecov:
  max_report_age: off
 
coverage:
  precision: 2
  range: "80...100"
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: auto
        base: auto
        threshold: 1%
        branches:
          - master
          - stageing
          - stable
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false